# Generated by Django 4.2 on 2023-04-22 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0002_alter_room_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='availability',
            field=models.BooleanField(default=True),
        ),
    ]
