# Generated by Django 4.2 on 2023-04-22 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0003_room_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='availability',
            field=models.BooleanField(default=False),
        ),
    ]
